swagger: "2.0"
info:
  description: "Marvel Characters API uses caches marvel characters data from [https://www.marvel.com/]"
  version: "1.0.0"
  title: "Marvel Characters API"
  contact:
    email: "ct.acampado@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
tags:
- name: "characters"
  description: "Get a list of character IDs or information about a specific character"
schemes:
- "http"
paths:
  /characters:
    get:
      tags:
      - "characters"
      summary: "Find all character IDs"
      description: "Returns all Marvel character IDs"
      operationId: "getCharacterIds"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CharIDs"
        "500":
          description: "server error"
  /characters/{id}:
    get:
      tags:
      - "characters"
      summary: "Find character by ID"
      description: "Returns a single Marvel character"
      operationId: "getCharacterById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of marvel character to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Character"
        "500":
          description: " error"
definitions:
  CharIDs:
    type: "array"
    items:
      type: "integer"
      format: "int64"
    example: [1009146,1014995,1009487,1011321,1011402,1009726]
  Character:
    type: "object"
    required:
    - "id"
    - "name"
    - "description"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: "1009146"
      name:
        type: "string"
        example: "Abomination (Emil Blonsky)"
      description:
        type: "string"
        example: "Formerly known as Emil Blonsky, a spy of Soviet Yugoslavian origin working for the KGB, the Abomination gained his powers after receiving a dose of gamma radiation similar to that which transformed Bruce Banner into the incredible Hulk."